export const futureThinking ={
  images: [
    {
      img: "./assets/images/future-thinking.jpg",
      alt: "Future Thinking",
      class: "slide-1"
    },
    {
      img: "./assets/images/future-thinking02.jpg",
      alt: "Future Thinking",
      class: "slide-2"
    },
    {
      img: "./assets/images/future-thinking03.jpg",
      alt: "Future Thinking",
      class: "slide-1"
    },
    {
      img: "./assets/images/future-thinking.jpg",
      alt: "Future Thinking",
      class: "slide-1"
    }
  ],

  list: [
    {
      item: "Grooming the best of people and leveraging the best of Technologies to build Web Systems."
    },
    {
      item: "Investing in the greatest of skill-sets and leveraging the most of the Resources."
    },
    {
      item: "Harnessing future-driven Web Technologies to automate Work-flows of Online Businesses and Services."
    },
    {
      item: "Creating end-to-end Web Solutions that are super speedy, reliable and safeguarded for complex, time-consuming and effort-taking Business Operations."
    },
    {
      item: "Creating Web Systems that can predict the future of the problems, challenges and issues of Businesses in a highly integrated infrastructure and virtual environment that resolves problems prior to their occurrence which reduces defects and errors and provides top class quality in the results being generated by our Systems."
    }
  ]
};
