export const automobileDb={
getAutomobileProjects(){
  let res={
    title : "Automobile",
    description :"<p>We provide Digital Solutions for Automobile Companies, Automobile Industries and Automobile Markets in India.</p> <p>Techprimelab renders specialized services in Automobile Zones that cater with Navigation Systems for Cars, Automobile Engineering, Automobile Repair, Automobile Sales and Automobile Calculators.</p>",
    projects :[
      /*{
       projectTitle:"KPIT UDD",
       projectDescription : "'Unified Data Dictionary' is an engineering data dictionary management tool which helps engineering users define the units, components & interfaces specific to release, phase and versions, which can be used during calibration and testing purposes of those components. Data generated by this tool will be finally consumed in System Desk and/or Matlab.",
       projectImg : "./assets/images/kpit-1.png",
       imgAlt : "KPIT UDD",
       class : "project-description"
       }*/
    ],

  };
  return Promise.resolve(res);
}
};
