export const informationTechnologyDb={
    title : "Information Technology",
    description :"<p>We are an IT software development company supporting online businesses with our software development services.</p><p>We create software development projects that brings to use the best of our big data analytics and software development workflows that resolve and deliver world class solutions.</p><p>Our strong software development environment grip-holds software development process models and tools that helps us deliver highly competent products to our clients.</p>",
    projects :[
      {
        projectTitle:"KPIT Klarity",
        projectDescription : "<p>KPIT&rsquo;s in-house MIS, &lsquo;KLARITY&rsquo; is available in the form of Web application and it shows similar dashboard user-interface for all projects.</p><p>With current system, the KPIT management who uses this dashboard, is not able to customize their dashboard as per their focus area.</p><p>Also there is no way they can change the scale or format of the graph as per their preference.</p><p>The company is willing to revamp this product with the help of latest technology to make it easily customizable for each project and for each manager, so that every manager should be able to decide his focus and rearrange his dashboard the way he likes.</p><p>He should be able to play with graph format and graph scale to get better understanding/analysis of the project status.</p><p>This development should be designed in a way that it should be usable for mobile application development in future.</p>",
        projectImg : "./assets/images/kpit-1.png",
        imgAlt : "KPIT Klarity",
        class : "project-description"
      },
      {
        projectTitle:"Cut2It Web",
        projectDescription : "<p>Cut2it is a media sharing platform that integrates into any digital media service and delivers a top notch consumer experience where you can dynamically synchronize comments and have a multi media discussion around a selected virtual video clip. </p><p>Cut2it gives you and your consumers a deeper experience and engagement providing longevity of your content which then can be shared across social media.</p><p>Cut2it drives consumer engagement, stickiness and incremental revenue for digital media though subscriptions and connects into third party advertising platforms.</p><p>Some key features are Digital media advanced interactive system, Synchronized notations and annotations, Virtual Clipping.</p>",
        projectImg : "./assets/images/cut2it-web.jpg",
        imgAlt : "Cut2It Web",
        class : "project-description float-right"
      },
      {
        projectTitle:"Cut2It Mobile",
        projectDescription : "<p>Cut2it is a media sharing platform that integrates into any digital media service and delivers a top notch consumer experience where you can dynamically synchronize comments and have a multi media discussion around a selected virtual video clip. </p><p>Cut2it gives you and your consumers a deeper experience and engagement providing longevity of your content which then can be shared across social media.</p><p>Cut2it drives consumer engagement, stickiness and incremental revenue for digital media though subscriptions and connects into third party advertising platforms.</p><p>Few key features are Digital media advanced interactive system, Synchronized notations and annotations, Virtual Clipping.</p>",
        projectImg : "./assets/images/cut2it.jpg",
        imgAlt : "Cut2It Mobile",
        class : "project-description"
      },
      {
        projectTitle:"Dataslice",
        projectDescription : "<p>Dataslice is a platform for creating survey for your research needs and analyzing it's result with different charts and reports.</p><p>It creates different types of surveys using simple user interface and with different in-built templates.</p><p>It distributes survey using email and collects all responses online. It creates different types of reports and charts for analytics and makes it available for emailing or downloading purpose in different formats.</p><p>The role management facility is also available in which different roles can be assigned to different users.</p>",
        projectImg : "./assets/images/dataslice.jpg",
        imgAlt : "Dataslice",
        class : "project-description float-right"
      }/*,
       {
       projectTitle:"KPIT UDD",
       projectDescription : "'Unified Data Dictionary' is an engineering data dictionary management tool which helps engineering users define the units, components & interfaces specific to release, phase and versions, which can be used during calibration and testing purposes of those components. Data generated by this tool will be finally consumed in System Desk and/or Matlab.",
       projectImg : "./assets/images/kpit-1.png",
       imgAlt : "KPIT UDD",
       class : "project-description"
       }*/,
      {
        projectTitle:"Peer-to-Peer Mobile Chat App",
        projectDescription : "<p>It is an in-house product of Techprimelab which enables users within same WiFi network to be able to chat with each other.</p><p>Through this mobile application, users from the same WiFi network can send invites to each other and once invites are accepted, easy, hassle-free chatting is possible along with easy media sharing.</p><p>This portal uses peer-to-peer data transfer approach which acclerates the data transfer to a large extent.</p>",
        projectImg : "./assets/images/peertopeer.png",
        imgAlt : "Peer-to-Peer Mobile Chat App",
        class : "project-description"
      }
    ],
};
