export const webDb={
    title : "Web",
    description :"Our web applications make web presence is most reachable for all types of businesses to grow and scale. We enable buying products and services over the web become more densely popular with time and necessity. We integrate web tools, features and utilities that extend a website to guarantee success. With the increasing popularity of portable devices, many now chose using our web applications rather than going through websites, for their needs or to get more information. We build web systems that make people prefer to buy products or access services without browsing an entire website. We create solutions that can be installed in your smart-phone, tablet or any other hand held device, to make it easier to use, access and work with.",
    projects :[
      {
        projectTitle:"Klotho.in",
        projectDescription : "Klotho.in is an eCommerce solution and also an agreegator for fashion industry. It includes boutiques, suppliers for fashion related materials and fashion photography. Currently primarily focusing on the Indian market however having a global approach since many facets of the process are reaching into international markets.",
        projectImg : "./assets/images/klotho.jpg",
        imgAlt : "Klotho.in",
        class : "project-description float-right"
      },
      {
        projectTitle:"KPIT Klarity",
        projectDescription : "KPIT’s in-house MIS, ‘KLARITY’ is available in the form of Web application and it shows similar dashboard user-interface for all projects. With current system, the KPIT management who uses this dashboard, is not able to customize their dashboard as per their focus area. Also there is no way they can change the scale or format of the graph as per their preference. The company is willing to revamp this product with the help of latest technology to make it easily customizable for each project and for each manager, so that every manager should be able to decide his focus and rearrange his dashboard the way he likes. He should be able to play with graph format and graph scale to get better understanding/analysis of the project status. This development should be designed in a way that it should be usable for mobile application development in future.",
        projectImg : "./assets/images/kpit-1.png",
        imgAlt : "KPIT Klarity",
        class : "project-description"
      }/*,
       {
       projectTitle:"KPIT UDD",
       projectDescription : "'Unified Data Dictionary' is an engineering data dictionary management tool which helps engineering users define the units, components & interfaces specific to release, phase and versions, which can be used during calibration and testing purposes of those components. Data generated by this tool will be finally consumed in System Desk and/or Matlab.",
       projectImg : "./assets/images/kpit-1.png",
       imgAlt : "KPIT UDD",
       class : "project-description float-right"
       }*/,
      {
        projectTitle:"Mybookfinds",
        projectDescription : "Mybookfinds is a portal enabling a web based platform mainly for authors after noticing need of credible & consistent means to promote their work. This also benefits the readers where they get various offers on e-books on popular social media outlets and also via email. Readers can set personal preferences on Mybookfinds and then will get notified by email with available deals on various leading sites which sell both e-books & printed media at one place. Mybookfinds does not sell books per say but it discovers discounted books from major sites like Amazon, Apple, Barnes & Noble and notify users based on their liking. To begin with, this portal is currently catering to US market and having long term plan to expand its operation to various other countries.",
        projectImg : "./assets/images/mybookfinds.jpg",
        imgAlt : "Mybookfinds",
        class : "project-description float-right"
      },
      {
        projectTitle:"Cut2It Web",
        projectDescription : "Cut2it is a media sharing platform that integrates into any digital media service and delivers a top notch consumer experience where you can dynamically synchronize comments and have a multi media discussion around a selected virtual video clip. Cut2it gives you and your consumers a deeper experience and engagement providing longevity of your content which then can be shared across social media. Cut2it drives consumer engagement, stickiness and incremental revenue for digital media though subscriptions and connects into third party advertising platforms. Some key features are Digital media advanced interactive system, Synchronized notations and annotations, Virtual Clipping.",
        projectImg : "./assets/images/cut2it-web.jpg",
        imgAlt : "Cut2It Web",
        class : "project-description"
      },
      {
        projectTitle:"Biomedtrics - Ditto",
        projectDescription : "Biomedtrics Inc. strives to help people with diabetes with their Ditto products. They continue to lead the mobile health technology industry using connectivity to make health management easier for people. Ditto is the first and only product to sync data from multiple glucose meters to both Android and iOS smartphones using a single Bluetooth device and securely store the data in a users mydittolife web account. The Ditto Glucose Data System, comprised of the Ditto Bluetooth devices, Android and iOS apps and HIPPA compliant mydittolife website, is FDA registered as a Class 1 medical device.",
        projectImg : "./assets/images/biomedtrics.jpg",
        imgAlt : "Biomedtrics - Ditto",
        class : "project-description float-right"
      },
      {
        projectTitle:"Patienet",
        projectDescription : "Patienet provides one place to store medical information with complete control and privacy to the user. This information stored by the user is accessible from anywhere anytime. HealthCare providers and patients are still storing information in different files and do not have instant access to the information. Patients need to carry all paper documents for their doctor visits. Patienet provides a platform which collaborates all data and communication at one place which is easily manageable and secured. Using this platform doctors and HealthCare professionals can communicate, set reminders, arrange follow ups and appointments for patients.",
        projectImg : "./assets/images/patienet.jpg",
        imgAlt : "Patienet",
        class : "project-description"
      },
      {
        projectTitle:"HireMatica",
        projectDescription : "Hirematica is the most effective employment background check service offering intuitive, reliable, FCRA-compliant solutions to meet the needs of organizations of any size. Various packages include: IDENTITY CHECK - We verify Social Security Number, name, aliases and previous addresses of the candidate for further investigation. CRIMINAL BACKGROUND - If the candidate has been convicted of a felony or serious misdemeanor, you’ll want to know the details. We check over 200 county, national databases to ensure your candidate’s past does not become a future liability for you. EMPLOYMENT CHECK - We confirm the candidate’s previous employment, title and salary (if available). EDUCATION CHECK - We validate the candidate’s latest school attendance, major and degree received. DRIVING RECORD - We check to see if the candidate has a valid driving license and a clean driving history.",
        projectImg : "./assets/images/hirematica.png",
        imgAlt : "HireMatica",
        class : "project-description float-right"
      },
      {
        projectTitle:"Source7",
        projectDescription : "Source7 is an eCommerce project built using Magento platform. Source7 is a portal aimed at the home building and improvement market, primarily focusing on the Indian market. However the long term goal is to have a global approach since many facets of the process are reaching into international markets. On this portal, all types of furniture for construction and interior decoration industry is available online.",
        projectImg : "./assets/images/source7.png",
        imgAlt : "Source7",
        class : "project-description"
      },
      {
        projectTitle:"Events Plugin",
        projectDescription : "TPL Events Manager is a extension for Magento, compatible with Magento version 1.7 to 1.9.X. This extension provides an easy and handy way of creating and managing various types of events with various permissions across your Magento store. These events can be made visible on frontend of store through event listing, event detail page and various widgets. Events can be created and managed from the admin panel.",
        projectImg : "./assets/images/Events-Plugin.png",
        imgAlt : "Events Plugin",
        class : "project-description float-right"
      },
      {
        projectTitle:"RentalRoost",
        projectDescription : "RentalRoost is the first house and apartment finding engine that generates predictive recommendations based on lifestyle. With over 20 search dimensions, RentalRoost’s proprietary patent-pending algorithms deliver an intuitive and precise search experience. Finding a rental property is a cumbersome process. Rental Roost helps you find your perfect home using search criteria that are important to you - walkability, kid-friendliness, pet-friendliness, proximity to public transportation, school district maps, zip codes and nearby restaurants, bars, shopping and entertainment.",
        projectImg : "./assets/images/rentalroost.png",
        imgAlt : "RentalRoost",
        class : "project-description"
      },
      {
        projectTitle:"Houserie",
        projectDescription : "Houserie.com is used by both individual landlords, as well as large property management companies, to screen potential tenants. Houserie.com provides numerous affordable screening packages ranging from an incredibly comprehensive screening report, including national criminal and eviction screening, to a basic credit screen in order to ensure that the tenant can afford the specified rent. Their screening products have proven to be a valuable tool to landlords in today’s competitive rental markets in selecting the most qualified tenant. In addition, their paperless process saves the landlord time by quickly providing a summary credit scorecard which helps landlords reduce their liability.",
        projectImg : "./assets/images/houserie.png",
        imgAlt : "Houserie",
        class : "project-description float-right"
      },
      {
        projectTitle:"Dataslice",
        projectDescription : "Dataslice is a platform for creating survey for your research needs and analyzing it's result with different charts and reports. It creates different types of surveys using simple user interface and with different in-built templates. It distributes survey using email and collects all responses online. It creates different types of reports and charts for analytics and makes it available for emailing or downloading purpose in different formats. The role management facility is also available in which different roles can be assigned to different users.",
        projectImg : "./assets/images/dataslice.jpg",
        imgAlt : "Dataslice",
        class : "project-description"
      },
      {
        projectTitle:"Mock2HTML",
        projectDescription : "Mock2HTML is our in-house product which enables the user to create/customise his own website using different technologies and skeletons available through this portal. The user can also access the options of a Responsive Layout, Google Optimization, Hosting Service, various Animations and Plugins. The web solutions built through this portal are SEO compliant as well as enhanced for a speedy, glitch-free performance.",
        projectImg : "./assets/images/mock2html.jpg",
        imgAlt : "Mock2HTML",
        class : "project-description float-right"
      },
      {
        projectTitle:"Thunder Expense Tracker",
        projectDescription : "Thunder Expense Tracker is a web based as well as mobile app based enterprise solution which can be used to track all types of organisation related expenses. This portal can be used individually also but its key strengths can be observed in an organisation based approach. Companies can set their expense budgets and track various expenses within various groups and control them in accordance with the budgets.",
        projectImg : "./assets/images/thunder.jpg",
        imgAlt : "Thunder Expense Tracker",
        class : "project-description"
      },
      {
        projectTitle:"Speech Recognition & Synthesis",
        projectDescription : "Speech Recognition and Speech Synthesis are the best technologies that not only evolve continuously but also used in today's web applications. As of today, they have the greatest impact on human interaction with machines. The simple motive behind this is: 'If I can speak why should I type!'. So Here at Techprimelab our Engineers are enhancing the Speech Recognition System by adding extra layer of Neural Network Learning Algorithms (both Unsupervised and Supervised) to fulfil the client's need in specific area such as Medical fields, Agriculture, Military Services etc. Our ultimate mission is to make Machine Interactions independent of external peripheral devices.",
        projectImg : "./assets/images/vociesearch.jpg",
        imgAlt : "Speech Recognition & Synthesis",
        class : "project-description float-right"
      },
      {
        projectTitle:"Test Precision",
        projectDescription : "SAT and ACT tests are widely taken by the students of the US. The need to provide those students a common portal where they can practice those tests and get used to the complex difficulty level trends of questions in those tests is what inspired the conception of 'Test Precision'. This product provides the students with various packages which contain large variety of tests. The algorithms for the difficulty level of the questions are created in a manner very close to the actual SAT and ACT tests. This product is available on web as well as app stores. The provision to continue your incomplete tests from any platform (web portal and app) to any other device adds great value to this product.",
        projectImg : "./assets/images/test-precision.jpg",
        imgAlt : "Test Precision",
        class : "project-description"
      },
      {
        projectTitle:"Addresses.io",
        projectDescription : "Addresses.io is simply 'Address Management Made Easy'. This web portal is primarily operational in US where it provides the users to access the API to verify their addresses at a very low cost. The tailor-made APIs that are available on this portal can be used in any third party application. Suggestive Search is one of the primary features of this portal where user can get a detailed information of any address just by typing a few keywords from that address.",
        projectImg : "./assets/images/addresses-io.jpg",
        imgAlt : "Addresses.io",
        class : "project-description float-right"
      }
    ],
};
